In [1]:
### Carregar as Libraries
import pandas as pd

### Importing Dataset
dataset = pd.read_csv('Madelon.csv',encoding='utf-8')

### Mostrando o dataset
dataset.head()

,a_0,a_1,a_2,a_3,a_4,a_5,a_6,a_7,a_8,a_9,...,a_491,a_492,a_493,a_494,a_495,a_496,a_497,a_498,a_499,class
0,485,477,537,479,452,471,491,476,475,473,...,481,477,485,511,485,481,479,475,496,-1
1,483,458,460,487,587,475,526,479,485,469,...,478,487,338,513,486,483,492,510,517,-1
2,480,491,510,485,495,472,417,474,502,476,...,480,474,572,454,469,475,482,494,461,1
3,484,502,528,489,466,481,402,478,487,468,...,479,452,435,486,508,481,504,495,511,1
4,481,496,451,480,516,484,484,476,500,482,...,481,477,435,491,564,482,463,457,500,1

In [2]:
# Obtendo todas as colnas, exceto a última
dataset_X = dataset.iloc[:, :-1]

### print(atributos)
X = dataset_X           # Features
y = dataset.iloc[:, -1] # Target

print(X)

      a_0  a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9  ...  a_490  a_491  \
0     485  477  537  479  452  471  491  476  475  473  ...    477    481
1     483  458  460  487  587  475  526  479  485  469  ...    463    478
2     480  491  510  485  495  472  417  474  502  476  ...    491    480
3     484  502  528  489  466  481  402  478  487  468  ...    488    479
4     481  496  451  480  516  484  484  476  500  482  ...    478    481
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...
2595  489  496  553  465  600  478  505  471  474  482  ...    466    476
2596  486  509  424  481  523  478  465  475  487  484  ...    485    476
2597  472  467  484  468  454  482  426  476  464  497  ...    483    478
2598  493  458  503  478  517  479  472  478  444  477  ...    469    475
2599  481  484  481  490  449  481  467  478  469  483  ...    506    485

      a_492  a_493  a_494  a_495  a_496  a_497  a_498  a_499
0       477    485    511    485    481    479    475    496
1       487    338    513    486    483    492    510    517
2       474    572    454    469    475    482    494    461
3       452    435    486    508    481    504    495    511
4       477    435    491    564    482    463    457    500
...     ...    ...    ...    ...    ...    ...    ...    ...
2595    480    698    452    463    477    460    487    458
2596    494    570    512    353    481    480    518    439
2597    473    479    487    477    474    495    538    492
2598    485    443    517    486    474    489    506    506
2599    508    599    498    527    481    490    455    451

[2600 rows x 500 columns]

In [3]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Columns: 500 entries, a_0 to a_499
dtypes: int64(500)
memory usage: 9.9 MB

In [4]:
m_values = X.isnull().sum()
m_values

a_0      0
a_1      0
a_2      0
a_3      0
a_4      0
        ..
a_495    0
a_496    0
a_497    0
a_498    0
a_499    0
Length: 500, dtype: int64

In [5]:
### Normalizando o dataset
from sklearn.preprocessing import StandardScaler

X_std = StandardScaler().fit_transform(X)
print(X_std)

print(X_std.shape)

[[ 0.51613623 -0.21597363  0.71307718 ... -0.30556792 -0.90311629
   0.2087788 ]
 [ 0.19926393 -0.84235166 -1.27190663 ...  0.64995023  0.04222888
   1.01890759]
 [-0.27604453  0.24556809  0.01704389 ... -0.08506373 -0.38992891
  -1.14143586]
 ...
 [-1.54353374 -0.54564628 -0.65321038 ...  0.87045442  0.79850501
   0.05446855]
 [ 1.78362544 -0.84235166 -0.16340918 ...  0.42944604 -0.06581057
   0.59455441]
 [-0.11760837  0.01479723 -0.73054741 ...  0.50294744 -1.44331352
  -1.52721148]]
(2600, 500)

In [10]:
### Importando PCA do SkLearn
from sklearn.decomposition import PCA

## Indicar o porcentagem de informação desejado
pca = PCA(n_components=0.75, whiten=True)

## Execução do PCA
pca_result = pca.fit_transform(X_std)

### Impressão do resultado
print(pca_result)
print(pca_result.shape)

[[ 1.95282215  0.26051373  1.19354699 ...  0.3633703   0.83793859
   1.52267651]
 [ 0.1813987  -1.28330442 -0.01890838 ... -0.55096115 -0.00582704
   0.39115693]
 [-1.13840952  0.83420682 -0.7662405  ... -0.19626023 -0.49672274
   0.24760315]
 ...
 [ 0.59611432 -0.0806099  -1.15439291 ...  0.15403462  0.83433362
  -0.51863619]
 [-0.64869161 -0.11928902  0.58181569 ... -0.65432505 -0.09116454
   1.10919898]
 [ 0.42343386  0.60816415 -0.8790802  ... -2.0716004   0.26984419
  -0.28321858]]
(2600, 277)

In [13]:
## Indicar o porcentagem de informação desejado
pca = PCA(n_components=0.90, whiten=True)

## Execução do PCA
pca_result = pca.fit_transform(X_std)

### Impressão do resultado
print(pca_result)
print(pca_result.shape)

[[ 1.95282215  0.26051373  1.19354699 ...  0.33661643 -0.843202
   1.32132423]
 [ 0.1813987  -1.28330442 -0.01890838 ... -0.63464293  0.66194853
  -0.69051753]
 [-1.13840952  0.83420682 -0.7662405  ...  0.71400448 -1.2180895
  -2.03618034]
 ...
 [ 0.59611432 -0.0806099  -1.15439291 ...  1.17035244  0.25263127
  -0.27248   ]
 [-0.64869161 -0.11928902  0.58181569 ...  0.96931102 -0.17096619
  -0.3728211 ]
 [ 0.42343386  0.60816415 -0.8790802  ...  1.35648639  0.93351643
  -0.56914025]]
(2600, 381)

In [16]:
## Indicar o número de componentes
pca = PCA(n_components = 100)

## Execução do PCA
pca_result = pca.fit_transform(X_std)

### Impressão do resultado
print(pca_result)
print(pca_result.shape)

[[ 4.96133031  0.58451103  2.46477667 ...  0.47765586 -1.73427
  -1.33604846]
 [ 0.45982404 -2.86380496 -0.04919848 ...  0.86205055 -0.39814373
  -0.94003794]
 [-2.89098652  1.87099571 -1.58464905 ...  1.13696467  0.04666496
   0.83460478]
 ...
 [ 1.51635054 -0.1846758  -2.39178845 ... -0.75459743 -0.86735863
   1.41131512]
 [-1.64333498 -0.27096212  1.21721863 ...  0.9427315   1.44519084
  -0.59173384]
 [ 1.07642672  1.36109816 -1.80612762 ...  0.21653431 -0.26435606
   1.94065187]]
(2600, 100)

In [17]:
### Colocando o nome nos atributos
i = 1
atributos = []
while i <= pca_result.shape[1]:
  atributos.append('pca_'+str(i))
  i += 1

pca_dataset = pd.DataFrame(data = pca_result, columns = atributos)

In [18]:
## Juntando o atributo classe
final_data = pca_dataset.join(y)

# Visualização dos dados normalizados
final_data.head()

# Salvando Pessoa.csv transformado
df = pd.DataFrame(final_data)
df.to_csv('Madelon_PCA-100.csv', index=False)

In [19]:
### Carregar as Libraries
import pandas as pd

### Importing Dataset
dataset = pd.read_csv('Arrhythmia.csv',encoding='utf-8')

### Mostrando o dataset
dataset.head()

,att0,att1,att2,att3,att4,att5,att6,att7,att8,att9,...,att269,att270,att271,att272,att273,att275,att276,att277,att278,class
0,0.903614,0,0.125926,0.435294,0.270677,0.368321,0.501805,0.241758,0.590244,0.457478,...,0.638554,1.0,0.381356,0.968531,0.0,0.53125,0.741667,0.507519,0.569579,8
1,0.674699,1,0.088889,0.341176,0.195489,0.332061,0.610108,0.150183,0.190244,0.577713,...,0.614458,1.0,0.360169,1.000000,0.0,0.31250,0.675000,0.485714,0.500971,6
2,0.650602,0,0.099259,0.523529,0.624060,0.311069,0.555957,0.282051,0.497561,0.785924,...,0.783133,1.0,0.402542,0.916084,0.0,0.34375,0.783333,0.424812,0.566990,10
3,0.662651,0,0.103704,0.517647,0.338346,0.385496,0.534296,0.260073,0.697561,0.586510,...,0.686747,1.0,0.516949,0.923077,0.0,0.37500,0.716667,0.592481,0.648544,1
4,0.903614,0,0.125926,0.435294,0.248120,0.345420,0.462094,0.252747,0.502439,0.457478,...,0.626506,1.0,0.555085,0.874126,0.0,0.21875,0.825000,0.523308,0.656311,7

In [20]:
# Obtendo todas as colnas, exceto a última
dataset_X = dataset.iloc[:, :-1]

### print(atributos)
X = dataset_X           # Features
y = dataset.iloc[:, -1] # Target

print(X)

         att0  att1      att2      att3      att4      att5      att6  \
0    0.903614     0  0.125926  0.435294  0.270677  0.368321  0.501805
1    0.674699     1  0.088889  0.341176  0.195489  0.332061  0.610108
2    0.650602     0  0.099259  0.523529  0.624060  0.311069  0.555957
3    0.662651     0  0.103704  0.517647  0.338346  0.385496  0.534296
4    0.903614     0  0.125926  0.435294  0.248120  0.345420  0.462094
..        ...   ...       ...       ...       ...       ...       ...
447  0.638554     1  0.081481  0.376471  0.187970  0.379771  0.541516
448  0.445783     0  0.125926  0.464706  0.338346  0.261450  0.465704
449  0.433735     0  0.090370  0.364706  0.398496  0.335878  0.480144
450  0.385542     1  0.074074  0.288235  0.285714  0.202290  0.555957
451  0.939759     1  0.081481  0.376471  0.180451  0.242366  0.476534

         att7      att8      att9  ...    att268    att269    att270  \
0    0.241758  0.590244  0.457478  ...  0.660574  0.638554  1.000000
1    0.150183  0.190244  0.577713  ...  0.558747  0.614458  1.000000
2    0.282051  0.497561  0.785924  ...  0.583812  0.783133  1.000000
3    0.260073  0.697561  0.586510  ...  0.687206  0.686747  1.000000
4    0.252747  0.502439  0.457478  ...  0.587467  0.626506  1.000000
..        ...       ...       ...  ...       ...       ...       ...
447  0.168498  0.570732  0.395894  ...  0.328982  0.674699  1.000000
448  0.340659  0.356098  0.756598  ...  0.762924  0.614458  1.000000
449  0.315018  0.565854  0.255132  ...  0.000000  0.819277  1.000000
450  0.402930  0.307317  0.662757  ...  0.650653  0.698795  0.902439
451  0.109890  0.380488  0.586510  ...  0.535248  0.638554  1.000000

       att271    att272  att273   att275    att276    att277    att278
0    0.381356  0.968531     0.0  0.53125  0.741667  0.507519  0.569579
1    0.360169  1.000000     0.0  0.31250  0.675000  0.485714  0.500971
2    0.402542  0.916084     0.0  0.34375  0.783333  0.424812  0.566990
3    0.516949  0.923077     0.0  0.37500  0.716667  0.592481  0.648544
4    0.555085  0.874126     0.0  0.21875  0.825000  0.523308  0.656311
..        ...       ...     ...      ...       ...       ...       ...
447  0.182203  0.825175     0.0  0.46875  0.550000  0.299248  0.246602
448  0.661017  0.944056     0.0  0.37500  0.700000  0.618045  0.653722
449  0.690678  0.000000     0.0  0.71875  0.583333  0.000000  0.034951
450  0.508475  0.975524     0.0  0.40625  0.700000  0.520301  0.551456
451  0.440678  0.937063     0.0  0.40625  0.633333  0.492481  0.462136

[452 rows x 260 columns]

In [21]:
m_values = X.isnull().sum()
m_values

att0      0
att1      0
att2      0
att3      0
att4      0
         ..
att273    0
att275    0
att276    0
att277    0
att278    0
Length: 260, dtype: int64

In [22]:
### Normalizando o dataset
from sklearn.preprocessing import StandardScaler

X_std = StandardScaler().fit_transform(X)
print(X_std)

print(X_std.shape)

[[ 1.73443726 -1.1075202   0.64132962 ...  1.17773967  0.29460489
   1.07866772]
 [ 0.57931328  0.90291807 -0.03199417 ...  0.61612581  0.07960969
   0.50487505]
 [ 0.45771783 -1.1075202   0.15652995 ...  1.52874096 -0.52087815
   1.05701501]
 ...
 [-0.63661095 -1.1075202  -0.00506994 ... -0.15609219 -4.70948347
  -3.39261303]
 [-0.8797968   0.90291807 -0.30132732 ...  0.82672996  0.42063417
   0.92709874]
 [ 1.91682791  0.90291807 -0.16666983 ...  0.2651161   0.14633166
   0.18008438]]
(452, 260)

In [24]:
### Importando PCA do SkLearn
from sklearn.decomposition import PCA

## Indicar o porcentagem de informação desejado
pca = PCA(n_components=0.90, whiten=True)

## Execução do PCA
pca_result = pca.fit_transform(X_std)

### Impressão do resultado
print(pca_result)
print(pca_result.shape)

[[-3.04300676e-01 -3.24990934e-03  5.97589500e-01 ... -1.52710121e+00
  -7.46683745e-01 -9.26691740e-01]
 [ 1.89292051e-02  2.91414298e-01  6.78587856e-01 ...  4.05195139e-02
   3.37710400e-03 -3.45209924e-02]
 [ 1.15505290e+00 -2.38560577e+00  2.53457908e-01 ... -6.79103129e-01
   1.32788788e+00  2.31941274e+00]
 ...
 [-3.79534277e+00 -3.98310674e+00  1.59952274e+00 ...  9.16346883e-01
   1.23362366e+00  1.08324973e-01]
 [ 7.50469297e-01  6.23101524e-01  6.01638823e-01 ...  2.93679089e-02
  -1.27614288e+00  9.73903923e-02]
 [ 3.17249901e-01 -7.07882879e-03  9.37767023e-01 ...  4.37445314e-01
   9.56549576e-01 -6.46724439e-01]]
(452, 78)